#!/bin/bash
# By Kees C. Bakker - keestalkstech.com
# (c) 2017 / MIT 

# Gets the IP details for the adapter. First parameter is the adapter.
# If prameter is empty, eth0 will be used.

#get the adapter
ADAPTER=$1

#default to eth0 adapter
if [ -z "$ADAPTER" ]; then
ADAPTER=eth0
fi

#get the data for the adapter
ADDRESS=$(ifconfig | grep -Pzo "$ADAPTER.*\n.*")

#check not found
if [ -z "$ADDRESS" ]; then
echo "Adapter '$ADAPTER' not found."
exit 1
fi

#ip is the first line
IP=$(echo $ADDRESS | egrep -o '([0-9]+\.?){4}' | head -n 1);

#bcast is the second line
BCAST=$(echo $ADDRESS | egrep -o '([0-9]+\.?){4}' | head -n 2 | tail -n 1);

#subnet is the third and last line
SUBNET=$(echo $ADDRESS | egrep -o '([0-9]+\.?){4}' | tail -n 1);

#gateway
GATEWAY=$(route -n | head -n 3 | tail -n 1 | egrep -o '[1-9][0-9]*\.([0-9]+\.?){3}')

#destination
DESTINATION=$(route -n | head -n 4 | tail -n 1 | egrep -o '[1-9][0-9]*\.([0-9]+\.?){3}' | head -n 1)

echo ""
echo "Data for '$ADAPTER':"
echo ""
echo "address $IP"
echo "netmask $SUBNET"
echo "network $DESTINATION"
echo "broadcast $BCAST"
echo "gateway $GATEWAY"
echo ""
